### ISSUE TITLE
Working only with groups

### ISSUE THREAD

**Issue by vainucleo** [ny4rlk0/Telegram-User-Add-Bot-Python#2]
Unfortunately the save.py only works with groups, not with channels.

It just works with channels where you have admin privileges

**Comment by ny4rlk0** [comment]
This two part explains why:

ChannelPrivateError 
The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it.

ChatAdminRequiredError 
Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group.

This is about telethons api which is not my code. It has limitations if you dont have permission to do than in that specific chat you cant as it explains at source.

https://github.com/LonamiWebs

Source: https://tl.telethon.dev/methods/channels/get_participants.html
